language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "WanjaADFGVX"
    token:
      secure: "9c8768f3a96b1fb99077361f8f49512bd511e6d0"

script:
  - ./gradlew build
  - ./gradlew sonarqube

cache:
  directories:
    - "$HOME/.gradle"
