language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "WanjaADFGVX"
    token:
      secure: "abed417b0f995114d2ccf5f3c1faefaf5b07e4e7"

script:
  - ./gradlew build
  - ./gradlew sonarqube

cache:
  directories:
    - "$HOME/.gradle"
